datagrid:
    family-variant-grid:
        options:
            entityHint: family_variant
            locale_parameter: localeCode
            manageFilters: false
        source:
            type: pim_datasource_family_variant
            repository_method: createDatagridQueryBuilder
        columns:
            label:
                label: Label
                frontend_type: label
            level_1:
                label: Variant axis level 1
                frontend_type: label
            level_2:
                label: Variant axis level 2
                frontend_type: label
        properties:
            id: ~
        filters:
            columns:
                label:
                    type: search
                    label: Label
                    data_name: translation.label
