extensions:
    pim-attribute-group-create-modal:
        module: pim/form/common/creation/modal
        config:
            labels:
                title: pim_enrich.index.attribute_group.create_btn
                subTitle: pim_menu.item.attribute_group
            successMessage: pim_enrich.entity.attribute_group.info.create_successfull
            editRoute: pim_enrich_attributegroup_edit
            postUrl: pim_enrich_attributegroup_rest_create
            modelKey: code
            routerKey: identifier
            method: PUT

    pim-attribute-group-create-form-cache-invalidator:
        module: pim/cache-invalidator
        parent: pim-attribute-group-create-modal
        position: 1000

    pim-attribute-group-create-code:
        module: pim/form/common/creation/field
        parent: pim-attribute-group-create-modal
        targetZone: fields
        position: 10
        config:
            identifier: code
            label: pim_enrich.entity.create_popin.code

    pim-attribute-group-create-form-properties-translation:
        module: pim/common/properties/translation
        parent: pim-attribute-group-create-modal
        targetZone: fields
        position: 100
        config:
            fieldBaseId: pim_enrich_attribute_group_form_label_
